; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "弹幕神器"
#define MyAppVersion "1.5.0"
#define MyAppPublisher "该昵称己被占用_"
#define MyAppURL "https://wsrj.pages.dev"
#define MyAppExeName "弹幕神器.exe"
#define ProjRoot ".."
#expr EmitLanguagesSection

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{7D0C5DB7-A6EA-40BB-9991-48B246B16089}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\desk-danmaku-vb
UninstallDisplayIcon={app}\{#MyAppExeName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile={#ProjRoot}\LICENSE
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir={#ProjRoot}\Installer\bin
; setup- <应用名> - <版本号> - <架构>
OutputBaseFilename=setup-deskdanmaku-v1.5.0-x86
SetupIconFile={#ProjRoot}\res\icon.ico
SolidCompression=yes
WizardStyle=classic light
DisableDirPage=no
DisableFinishedPage=no
DisableProgramGroupPage=no
DisableReadyMemo=no
DisableReadyPage=no
DisableStartupPrompt=yes
DisableWelcomePage=no
WizardImageFile={#ProjRoot}\Installer\res\bg_installer_left.bmp
WizardSmallImageFile={#ProjRoot}\Installer\res\bg_installer_topsmall.bmp

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; 运行 VB6 “Package & Development 向导”打包，把目录设置为 \Output\packages 即可得到以下文件
; （注意手动勾选清单文件，否则无法通过编译）
Source: "{#ProjRoot}\Output\bin\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ProjRoot}\Output\packages\Support\asycfilt.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ProjRoot}\Output\packages\Support\CMDLGCHS.DLL"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ProjRoot}\Output\packages\Support\COMCAT.DLL"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ProjRoot}\Output\packages\Support\COMDLG32.OCX"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ProjRoot}\Output\packages\Support\MSCMCCHS.DLL"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ProjRoot}\Output\packages\Support\MSCOMCTL.OCX"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ProjRoot}\Output\packages\Support\msvbvm60.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ProjRoot}\Output\packages\Support\msxml6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ProjRoot}\Output\packages\Support\oleaut32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ProjRoot}\Output\packages\Support\olepro32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ProjRoot}\Output\packages\Support\VB6CHS.DLL"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ProjRoot}\Output\packages\Support\VB6STKIT.DLL"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ProjRoot}\Output\packages\Support\弹幕神器.exe.manifest"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:ProgramOnTheWeb,{#MyAppName}}"; Filename: "{#MyAppURL}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

